Class {
	#name : #FamixTypeScriptGlobalVariable,
	#superclass : #FamixTypeScriptStructuralEntity,
	#traits : 'FamixTGlobalVariable',
	#classTraits : 'FamixTGlobalVariable classTrait',
	#category : #'Famix-TypeScript-Entities-Entities'
}

{ #category : #meta }
FamixTypeScriptGlobalVariable class >> annotation [

	<FMClass: #GlobalVariable super: #FamixTypeScriptStructuralEntity>
	<package: #FamixTypeScript>
	<generated>
	^self
]
